### ISSUE TITLE
Docker Unknown Flag

### ISSUE THREAD

**Issue by Ne0nd0g** [outflanknl/RedELK#60] opened 2020-10-06 18:08 UTC
The install ELK script for `RedELK version 2 - BETA 1` uses the invalid `--quiet` argument:

```
root@ELK:~/elkserver# docker pull --quiet jupyter/scipy-notebook
unknown flag: --quiet
See 'docker pull --help'.
root@ELK:~/elkserver# docker pull --help

Usage:	docker pull [OPTIONS] NAME[:TAG|@DIGEST]

Pull an image or a repository from a registry

Options:
  -a, --all-tags                Download all tagged images in the repository
      --disable-content-trust   Skip image verification (default true)
root@ELK:~/elkserver# docker version
Client:
 Version:           18.09.1
 API version:       1.39
 Go version:        go1.11.6
 Git commit:        4c52b90
 Built:             Sun, 14 Jun 2020 22:12:29 +0200
 OS/Arch:           linux/amd64
 Experimental:      false

Server:
 Engine:
  Version:          18.09.1
  API version:      1.39 (minimum version 1.12)
  Go version:       go1.11.6
  Git commit:       4c52b90
  Built:            Sun Jun 14 20:12:29 2020
  OS/Arch:          linux/amd64
  Experimental:     false
```

I just adjusted the script to remove the flag and continue on.

**Comment by MarcOverIP** [comment] 2020-10-06 18:17
Duplicate of issue #59

**Closed by MarcOverIP** 2020-10-06 18:17 UTC
