### ISSUE TITLE
New alarm: move Chameleon domain check to an alarm module

### ISSUE THREAD

**Issue by fastlorenzo** [outflanknl/RedELK#127] opened 2020-11-20 20:08 UTC
The current setup with Chameleon should be migrated to an alarm module

**Comment by MarcOverIP** [comment] 2020-11-27 15:34
Is this a duplicate of #131 or is this a different approach?

**Comment by fastlorenzo** [comment] 2020-12-02 10:28
Linked to #131  indeed, Chameleon would be part of that alarm and thus should be moved in that specific alarm folder

**Comment by fastlorenzo** [comment] 2021-11-18 23:11
@MarcOverIP we should close this one as this is the same as #131 (to avoid duplicate issues)

**Closed** 2021-11-19 00:54 UTC
Labels: enhancement, elkserver, alarm
